"""add primary keys on middle table and nullable options

Revision ID: fdb12c829438
Revises: 
Create Date: 2021-11-09 02:56:41.169625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdb12c829438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_countries', 'company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('company_countries', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('company_tags', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('company_tags', 'company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('company_tags', 'tag_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('country_tags', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('country_tags', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('country_tags', 'tag_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_tags', 'tag_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('country_tags', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('country_tags', 'id')
    op.alter_column('company_tags', 'tag_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('company_tags', 'company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('company_tags', 'id')
    op.alter_column('company_countries', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('company_countries', 'company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
